### ISSUE TITLE
Release 22.06

### ISSUE THREAD

**Issue by maltesander** [stackabletech/release#7]
# Operator versions
- [x] Airflow: 0.4.0 https://github.com/stackabletech/airflow-operator/pull/123 https://github.com/stackabletech/airflow-operator/pull/125
- [x] Commons: 0.2.0 https://github.com/stackabletech/commons-operator/pull/53 https://github.com/stackabletech/commons-operator/pull/54
- [x] Druid: 0.6.0 https://github.com/stackabletech/druid-operator/pull/259 https://github.com/stackabletech/druid-operator/pull/260
- [x] Hbase: 0.3.0 https://github.com/stackabletech/hbase-operator/pull/199 https://github.com/stackabletech/hbase-operator/pull/201
- [x] Hdfs: 0.4.0 https://github.com/stackabletech/hdfs-operator/pull/200 https://github.com/stackabletech/hdfs-operator/pull/201
- [x] Hive: 0.6.0 https://github.com/stackabletech/hive-operator/pull/199 https://github.com/stackabletech/hive-operator/pull/201
- [x] Kafka: 0.6.0 https://github.com/stackabletech/kafka-operator/pull/423 https://github.com/stackabletech/kafka-operator/pull/424
- [x] NiFi: 0.6.0 https://github.com/stackabletech/nifi-operator/pull/292 https://github.com/stackabletech/nifi-operator/pull/295
- [x] OPA 0.9.0: https://github.com/stackabletech/opa-operator/pull/308 https://github.com/stackabletech/opa-operator/pull/310
- [x] Secret: 0.5.0 https://github.com/stackabletech/secret-operator/pull/149 https://github.com/stackabletech/secret-operator/pull/150
- [x] Spark-k8s: 0.3.0 https://github.com/stackabletech/spark-k8s-operator/pull/93 https://github.com/stackabletech/spark-k8s-operator/pull/95
- [x] Superset: 0.5.0 https://github.com/stackabletech/superset-operator/pull/223 https://github.com/stackabletech/superset-operator/pull/224
- [x] Trino: 0.4.0 https://github.com/stackabletech/trino-operator/pull/228 https://github.com/stackabletech/trino-operator/pull/229
- [x] ZooKeeper: We already released 0.10.0 on 23.06.2022, not going to release again

# New Versions

- [x] druid - 0.23.0
   - [x] tested with operator and local image 
   - [x] examples adapted
   - [x] integration tests added
   - [x] supported versions added
   - [x] docker image created
   - [x] documentation adapted
- [x] hadoop - 3.3.3
   - [x] tested with operator and local image 
   - [x] examples adapted
   - [x] integration tests added
   - [x] supported versions added
   - [x] docker image created
   - [x] documentation adapted
- [x] hbase - 2.4.12
   - [x] tested with operator and local image 
   - [x] examples adapted
   - [x] integration tests added
   - [x] supported versions added
   - [x] docker image created
   - [x] documentation adapted
- [x] kafka - 2.13-3.2.0
   - [x] tested with operator and local image 
   - [x] examples adapted
   - [x] integration tests added
   - [x] supported versions added
   - [x] docker image created
   - [x] documentation adapted
- [x] opa - 0.41.0
   - [x] tested with operator and local image 
   - [x] examples adapted
   - [x] integration tests added
   - [x] supported versions added
   - [x] docker image created
   - [x] documentation adapted
- [x] nifi - 1.16.3
   - [x] tested with operator and local image 
   - [x] examples adapted
   - [x] integration tests added
   - [x] supported versions added
   - [x] docker image created
   - [x] documentation adapted
- [x] spark-k8s - 3.3.0
   - [x] tested with operator and local image 
   - [x] examples adapted
   - [x] integration tests added
   - [x] supported versions added
   - [x] docker image created
   - [x] documentation adapted
- [x] superset - 1.5.1
   - [x] tested with operator and local image 
   - [x] examples adapted
   - [x] integration tests added
   - [x] supported versions added
   - [x] docker image created
   - [x] documentation adapted
- [x] trino - 387
   - [x] tested with operator and local image 
   - [x] examples adapted
   - [x] integration tests added
   - [x] supported versions added
   - [x] docker image created
   - [x] documentation adapted

**Comment by lfrancke** [comment]
@maltesander Can this be closed? I guess so?

**Comment by maltesander** [comment]
Yeah closing it.
